name: New features

on:
  push:
    branches:
      - "feature/*"
    paths-ignore:
      - "LICENSE"
      - "*.md"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Project Files
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Compile, Build and Test environment
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Compile, Build and Test
      run: ./build.sh

    - name: Slack Msg
      env:
          SLACK_SECRET: ${{ secrets.SLACK_SECRET }}
      run: ./notify.sh